parameters:
  ite_cron.manager.class: ITE\CronBundle\Cron\CronManager
  ite_cron.cache_warmer.class: ITE\CronBundle\CacheWarmer\CronListenerCacheWarmer
  ite_cron.file_loader.class: ITE\CronBundle\Loader\FileLoader
  ite_cron.command_reference.class: ITE\CronBundle\Cron\Reference\CommandReference
  ite_cron.listener_reference.class: ITE\CronBundle\Cron\Reference\ListenerReference
  ite_cron.reference_factory.class: ITE\CronBundle\Cron\Reference\ReferenceFactory

services:
  ite_cron.manager:
    class: %ite_cron.manager.class%
    arguments: [@ite_cron.file_loader, %kernel.cache_dir%]

  ite_cron.cache_warmer:
    class: %ite_cron.cache_warmer.class%
    arguments: [@ite_cron.manager]
    tags: [{ name: kernel.cache_warmer }]

  ite_cron.file_loader:
    class: %ite_cron.file_loader.class%
    arguments: [@file_locator]

  ite_cron.command_reference:
    class: %ite_cron.command_reference.class%
    factory: [%ite_cron.reference_factory.class%, createCommandReference]

  ite_cron.listener_reference:
    class: %ite_cron.listener_reference.class%
    factory: [%ite_cron.reference_factory.class%, createListenerReference]